services:
  heemo-db:
    image: postgres:16-alpine
    container_name: heemo-db
    environment:
      POSTGRES_DB: heemo
      POSTGRES_USER: heemo_user
      POSTGRES_PASSWORD: heemo_password
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data

  heemo-redis:
    image: redis:7-alpine
    container_name: heemo-redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
