spring:
  application:
    name: Heemo-API
  
  # 기능별 설정 파일 임포트 (application- 접두어 제거됨)
  config:
    import:
      - optional:postgresql.yaml
      - optional:redis.yaml

  # 기본 프로파일 설정 (여기서 변경 가능)
  profiles:
    active: local

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 20215482618-vv77f6f2jrgkgrjutdqe331ek28qbeuh.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          kakao:
            client-id: 0199bd6766ecdb931c2f0ee387b06ed7
            client-secret: HRVhM2f4PxOPuYDMQkxcPHqQrneytzdL
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile_nickname
              - profile_image
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: v7s8w9x0z1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0
  access-token-validity-in-seconds: 3600 # 1시간
  refresh-token-validity-in-seconds: 1209600 # 14일

app:
  oauth2:
    authorized-redirect-uri: http://localhost:3000/oauth2/redirect # 프론트엔드 리다이렉트 주소

---
# --- Prod Profile ---
spring:
  config:
    activate:
      on-profile: prod

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
