spring:
  application:
    name: Heemo-API
  
  # 기능별 설정 파일 임포트
  config:
    import:
      - optional:application-database.yaml
      - optional:application-redis.yaml

  # 기본 프로파일 설정
  profiles:
    active: local